insert into server (id, name, description) values (26, 'Server A', 'Description of Server A');
insert into server (id, name, description) values (25, 'Server B', 'Description of Server B');
insert into server (id, name, description) values (24, 'Server C', 'Description of Server C');
insert into server (id, name, description) values (23, 'Server D', 'Description of Server D');
-- insert into server (id, name, description) values (22, 'Server E', 'Description of Server E');
-- insert into server (id, name, description) values (21, 'Server F', 'Description of Server F');
-- insert into server (id, name, description) values (20, 'Server G', 'Description of Server G');
-- insert into server (id, name, description) values (19, 'Server H', 'Description of Server H');
-- insert into server (id, name, description) values (18, 'Server I', 'Description of Server I');
-- insert into server (id, name, description) values (17, 'Server J', 'Description of Server J');
-- insert into server (id, name, description) values (16, 'Server K', 'Description of Server K');
-- insert into server (id, name, description) values (15, 'Server L', 'Description of Server L');
-- insert into server (id, name, description) values (14, 'Server M', 'Description of Server M');
-- insert into server (id, name, description) values (13, 'Server N', 'Description of Server N');
-- insert into server (id, name, description) values (12, 'Server O', 'Description of Server O');
-- insert into server (id, name, description) values (11, 'Server P', 'Description of Server P');
-- insert into server (id, name, description) values (10, 'Server Q', 'Description of Server Q');
-- insert into server (id, name, description) values (9, 'Server R', 'Description of Server R');
-- insert into server (id, name, description) values (8, 'Server S', 'Description of Server S');
-- insert into server (id, name, description) values (7, 'Server T', 'Description of Server T');
-- insert into server (id, name, description) values (6, 'Server U', 'Description of Server U');
-- insert into server (id, name, description) values (5, 'Server V', 'Description of Server V');
-- insert into server (id, name, description) values (4, 'Server W', 'Description of Server W');
-- insert into server (id, name, description) values (3, 'Server X', 'Description of Server X');
-- insert into server (id, name, description) values (2, 'Server Y', 'Description of Server Y');
-- insert into server (id, name, description) values (1, 'Server Z', 'Description of Server Z');
